#include QMK_KEYBOARD_H

#include "features/caps_word.h"

bool process_record_user(uint16_t keycode, keyrecord_t* record) {
  if (!process_caps_word(keycode, record)) { return false; }
  // Your macros ...

  return true;
}

// alt, super, shift, ctrl
const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
	[0] = LAYOUT_split_3x6_3(KC_TAB, KC_Q, KC_W, KC_E, KC_R, KC_T, KC_Y, KC_U, KC_I, KC_O, KC_P, KC_BSLS, KC_ESC, MT(MOD_LALT, KC_A), MT(MOD_LGUI, KC_S), MT(MOD_LSFT, KC_D), MT(MOD_LCTL, KC_F), KC_G, KC_H, MT(MOD_RCTL, KC_J), MT(MOD_RSFT, KC_K), MT(MOD_RGUI, KC_L), MT(MOD_RALT, KC_SCLN), KC_QUOT, KC_GRV, KC_Z, KC_X, KC_C, KC_V, KC_B, KC_N, KC_M, KC_COMM, KC_DOT, KC_SLSH, KC_EQL, LT(2,KC_NO), LT(1,KC_DEL), KC_BSPC, KC_ENT, LT(3,KC_SPC), LT(4,KC_NO)),
	[1] = LAYOUT_split_3x6_3(KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_PSLS, KC_7, KC_8, KC_9, KC_PMNS, KC_NO, KC_NO, MOD_LALT, MOD_LGUI, MOD_LSFT, MOD_LCTL, KC_NO, KC_PAST, KC_4, KC_5, KC_6, KC_PPLS, KC_PEQL, KC_NO, KC_NO, KC_HYPR, KC_MEH, KC_NO, KC_NO, KC_PCMM, KC_1, KC_2, KC_3, KC_PDOT, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_0),
	[2] = LAYOUT_split_3x6_3(KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_VOLU, KC_MFFD, KC_NO, MOD_LALT, MOD_LGUI, MOD_LSFT, MOD_LCTL, KC_NO, KC_LEFT, KC_DOWN, KC_UP, KC_RGHT, KC_VOLD, KC_MRWD, KC_NO, KC_NO, KC_HYPR, KC_MEH, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_MUTE, KC_MPLY, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO),
	[3] = LAYOUT_split_3x6_3(KC_NO, KC_CIRC, KC_AMPR, KC_RCBR, KC_RBRC, KC_AT, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_PERC, KC_EXLM, KC_LCBR, KC_LBRC, KC_HASH, KC_NO, MOD_LCTL, MOD_LSFT, MOD_LGUI, MOD_LALT, KC_NO, KC_NO, KC_NO, KC_TILD, KC_DLR, KC_RPRN, KC_PIPE, KC_NO, KC_NO, KC_MEH, KC_HYPR, KC_NO, KC_NO, KC_NO, KC_LPRN, KC_UNDS, KC_NO, KC_NO, KC_NO),
	[4] = LAYOUT_split_3x6_3(KC_NO, KC_F12, KC_F7, KC_F8, KC_F9, KC_PSCR, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_INS, KC_F11, KC_F4, KC_F5, KC_F6, KC_PGUP, KC_NO, MOD_LCTL, MOD_LSFT, MOD_LGUI, MOD_LALT, KC_NO, KC_NO, KC_F10, KC_F1, KC_F2, KC_F3, KC_PGDN, KC_NO, KC_NO, KC_MEH, KC_HYPR, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO)
};

